#!/usr/bin/env bash

# bemenu theming
lines="-l 20"
font="-fn Inconsolata-13"
colors="-nb #2C323E -nf #9899a0 -sb #BF616A -sf #2C323E"

ask_yes() {
	local prompt="$*"

	local answer="$(echo -e "Yes\nNo" |
		bemenu -i -p "$prompt" \
			$lines $colors $font)"
	if [[ "$answer" == "Yes" ]]; then
		echo "Yes"
	fi
}

selected="$(ps -a -u $USER |
	bemenu -i -p "Type to search and select process to kill" \
		$lines $colors $font |
	awk '{print $1" "$4}')"

if [[ ! -z $selected ]]; then

	answer="$(ask_yes $selected will be killed, are you sure?)"
	if [[ "$answer" ]]; then
		selpid="$(awk '{print $1}' <<<$selected)"
		kill $selpid
		sleep 2
		if ps -p $selpid >/dev/null; then
			answer="$(ask_yes $selected is still running, do you want to force kill?)"
			if [[ "$answer" ]]; then
				kill -9 $selpid
			fi
		fi
	fi
fi

exit 0
