#!/usr/bin/env bash

tempdir=$(mktemp -d)
function cleanup {
	rm -rf "$tempdir"
}

trap cleanup EXIT
trap cleanup SIGINT

if [[ "$1" ]]; then
	dir="$1"
	cd "$dir" || exit
else
	dir=.
fi

export FD_ARGS="$tempdir/fzf-finder.fd-args"
export LAST_QUERY="$tempdir/fzf-finder.last-query"
echo "-t f" >$FD_ARGS
touch $LAST_QUERY
show_fzf() {
	fzf --preview-window '~3' \
		--bind "tab:execute-silent(echo {q} > $LAST_QUERY)+clear-query+disable-search+change-preview:($HOME/.config/util/rg_command {q} {} | fmt -s -w \$(echo \"\$(tput cols) / 2.25\" | bc))" \
		--bind "btab:transform-query(cat $LAST_QUERY)+enable-search+change-preview:" \
		--bind "ctrl-t:reload($HOME/.config/util/fd_command $dir -t d -t f)+execute-silent(echo '-t d -t f' > $FD_ARGS)" \
		--bind "ctrl-w:reload($HOME/.config/util/fd_command $dir -t f)+execute-silent(echo '-t f' > $FD_ARGS)" \
		--bind "ctrl-d:execute-silent(rm -f {} || rmdir {})+reload($HOME/.config/util/fd_command $dir \$(cat $FD_ARGS))" \
		--bind "ctrl-l:execute($EDITOR {} >&2)" \
		--bind "ctrl-f:execute(echo -e '{q}\n..')+abort" \
		--bind "ctrl-p:execute(echo -e '\n{q}')+abort" \
		--prompt="$(realpath -s $dir) > " \
		--query="$(cat $LAST_QUERY)" \
		--print-query
}
search() {
	export FZF_DEFAULT_COMMAND="$HOME/.config/util/fd_command $dir $(cat $FD_ARGS)"
	readarray -t results <<<"$(show_fzf)"
	echo "${results[0]}" >$LAST_QUERY
	selected="${results[1]}"
	if [[ ! -f "$selected" && "$selected" ]]; then
    [[ "$selected" == "~" ]] && selected="$HOME"
		if [[ -d "$selected" ]]; then
			cd "$selected" || exit
			dir="$PWD"
		fi
		export FZF_DEFAULT_COMMAND="$HOME/.config/util/fd_command $dir $(cat $FD_ARGS)"
		search
	fi
}
search
xdg-open "$selected"
