wtf:
  colors:
    border:
      focusable: darkslateblue
      focused: orange
      normal: gray
  grid:
    columns: [17, 30]
    rows: [4, 6]
  refreshInterval: 10s
  mods:
    clocks_a:
      enabled: true
        
      position:
        top: 0
        left: 0
        height: 1
        width: 1
      refreshInterval: 5
      title: "Date"
      args: ["+%d/%m/%y %H:%M"]
      cmd: "date"
      type: cmdrunner
    Music:
      title: "Music"
      args: ["-c","mpc -f '[[%title%] - %artist%]|[%filename%]'"]
      cmd: "sh"
      enabled: true
      position:
        top: 0
        left: 1
        height: 1
        width: 1
      refreshInterval: 1s
      type: cmdrunner
    resourceusage:
      title: "Resources"
      cpuCombined: true
      enabled: true
      position:
        top: 1
        left: 0
        height: 1
        width: 2
      refreshInterval: 1s
      showCPU: true
      showMem: true
      showSwp: true
      type: resourceusage



