#!/usr/bin/env bash

tempdir=$(mktemp -d)
function cleanup {
	rm -rf "$tempdir"
}

trap cleanup EXIT
trap cleanup SIGINT

if [[ "$1" ]]; then
	dir="$1"
	cd "$dir" || exit
else
	dir=.
fi

export FD_ARGS="$tempdir/fzf-finder.fd-args"
export LAST_QUERY="$tempdir/fzf-finder.last-query"
echo "-t f" >$FD_ARGS
touch $LAST_QUERY
show_fzf() {
	fzf --preview-window '~3' \
		--bind "tab:execute-silent(echo {q} > $LAST_QUERY)+clear-query+disable-search+change-preview:(rg_command {q} {} | fmt -s -w \$(echo \"\$(tput cols) / 2.25\" | bc))" \
		--bind "btab:transform-query(cat $LAST_QUERY)+enable-search+change-preview:" \
		--bind "ctrl-t:reload(fd_command  -d $dir -- -t d -t f)+execute-silent(echo '-t d -t f' > $FD_ARGS)" \
		--bind "ctrl-w:reload(fd_command -d $dir -- -t f)+execute-silent(echo '-t f' > $FD_ARGS)" \
		--bind "ctrl-d:execute-silent(rm -f {} || rmdir {})+reload(fd_command -d $dir -- \$(cat $FD_ARGS))" \
		--bind "ctrl-l:execute($EDITOR {})" \
		--bind "ctrl-f:become:echo '{q}\n..'; exit 1" \
		--bind "ctrl-p:become:echo '\n{q}'; exit 1" \
		--prompt="$(realpath -s $dir) > " \
		--query="$(cat $LAST_QUERY)" \
		--print-query 2>&1
}
search() {
	export FZF_DEFAULT_COMMAND="fd_command -d $dir -- $(cat $FD_ARGS)"
	readarray -t results <<<"$(show_fzf)"
	echo "${results[0]}" >$LAST_QUERY
	selected="${results[1]}"
	if [[ ! -f "$selected" && "$selected" ]]; then
    [[ "$selected" == "~" ]] && selected="$HOME"
		if [[ -d "$selected" ]]; then
			cd "$selected" || exit
			dir="."
		fi
		export FZF_DEFAULT_COMMAND="fd_command -d $dir -- $(cat "$FD_ARGS")"
		search
	fi
}
search
xdg-open "$selected"
