#!/usr/bin/env bash

## This script allows to enable/disable/toggle the touchpad in hyprland sessions.
## Each user has its own XDG_RUNTIME_DIR, so this script will
## run in all of them.
##
## Note that this script will only work for the first hyprland session running for each user.

# enables/disables the touchpad for all hyprland sessions.

notify_timeout=5000
notify_color=blue

for_each_session() {
	for user in $(users); do
		uid=$(id -u $user)
		export XDG_RUNTIME_DIR=/run/user/$uid
		if [[ -d $XDG_RUNTIME_DIR/hypr ]]; then
			session=$(check_session) || continue
			echo "----- Found XDG_RUNTIME_DIR: $XDG_RUNTIME_DIR -----"
			echo "----- Running for user: $user -----"
			echo "----- Hyprland version: $session -----"
			touchpad_process_action "$@"
		fi
	done
}

# Calls the hyprctl command for the first hyprland session.
hypr() {
	hyprctl -i 0 "$@"
}

# Checks if a hyprland session is running.
check_session() {
	session=$(hypr version)
	if ! [[ $? -eq 0 ]]; then
		echo "No hyprland session found." >&2
		return 1
	else
		echo $session
	fi
}

# Gets the touchpad device name.
get_touchpad_device() {
	dev=$(hypr devices | grep -Eo "[^ ]+touchpad")
	if ! [[ "$dev" ]]; then
		echo "No touchpad device was found." >&2
		return 2
	fi
	echo $dev
}

# Does the actual touchpad action (enable/disable/toggle).
touchpad_action() {
	TOUCHPAD_DEVICE="$1"
	TODO_ACTION="$2"

	action_int=0 # 0 = disable, 1 = enable
	[[ "$TODO_ACTION" == "enable" ]] && action_int=1
	hypr keyword "device[$TOUCHPAD_DEVICE]:enabled" $action_int  # Enables/disables the touchpad
	hypr keyword input:touchpad:disable_while_typing $action_int # Indicates if the touchpad is currently enabled or disabled

	hypr notify 1 $notify_timeout "$notify_color" "Touchpad $TOUCHPAD_DEVICE ${TODO_ACTION}d by touchpadctl."
	echo "Touchpad $TOUCHPAD_DEVICE ${TODO_ACTION}d"
}

# Processes the touchpad action and calls the touchpad_action function.
# The 'toggle' action will only work correctly if there is only one touchpad device
# (I really don't know why someone would have more than one). Due to a hyprctl issue.
# https://github.com/hyprwm/Hyprland/issues/5724
touchpad_process_action() {

	ACTION="$1"
	TOUCHPAD_DEVICE=$(get_touchpad_device)

	if [ $? -ne 0 ]; then
		return 2
	fi

	echo "Considering $TOUCHPAD_DEVICE as touchpad."

	TODO_ACTION=$ACTION
	if [ $ACTION == "toggle" ]; then
		current_state=$(hypr getoption input:touchpad:disable_while_typing | grep "int: " | cut -d " " -f 2)
		if [[ $current_state == "1" ]]; then
			TODO_ACTION="disable"
		else
			TODO_ACTION="enable"
		fi
	fi

	touchpad_action "$TOUCHPAD_DEVICE" "$TODO_ACTION"
}

action=$1
if [[ "$action" != "enable" && "$action" != "disable" && "$action" != "toggle" ]]; then
	echo "Usage: $0 [enable|disable|toggle]" >&2
	exit 1
fi

for_each_session "$@"
