#!/usr/bin/env bash

operation=$1
arg=$2

WOBSOCK=$XDG_RUNTIME_DIR/${XDG_CURRENT_DESKTOP}_volume.sock
case "$operation" in
init)

	pgrep -a "tail" | grep -F -- "$XDG_RUNTIME_DIR/${XDG_CURRENT_DESKTOP}" | awk '{print $1}' | xargs kill
	rm -rf "$WOBSOCK"
	mkfifo "$WOBSOCK"
	tail "$WOBSOCK" -f | wob

	;;
up)
	pamixer -i "$arg"
	pamixer --get-volume >"$WOBSOCK"
	;;
down)
	pamixer -d "$arg"
	pamixer --get-volume >"$WOBSOCK"
	;;
esac
